### PR TITLE
Client GET,POST,PUT,DELETE wrapper to call method.

### PR DESCRIPTION
**Pull request by mediafigaro**
Hello, thanks for this lib, I just added a small wrapper.

### CODE REVIEW

**Comment by f3ath** [comment]
@mediafigaro Thank you for the PR. Can you please elaborate on the purpose if this change? Also, you might want to be interested in [HttpClient](https://github.com/phpcurl/curlhttp) which I also maintain.

**Comment by mediafigaro** [comment]
Just to simplify calls replacing $appnexus->call('GET', '/campaign') by $appnexus->get( '/campaign') . Ok, don't you use Guzzle ?

**Comment by f3ath** [comment]
@mediafigaro could you please add tests for this change? Also, please make sure the code style matches the one used in the project (spaces, line breaks, etc)

**Comment by f3ath** [comment]
No traction

**Pull request closed without merging**
